language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ytodorov/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ytodorov/react-test npm test

after_success:
  - docker build -t ytodorov93/client-img ./client
  - docker build -t ytodorov93/nginx-img ./nginx
  - docker build -t ytodorov93/server-img ./server
  - docker build -t ytodorov93/worker-img ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push ytodorov93/client-img
  - docker push ytodorov93/nginx-img
  - docker push ytodorov93/server-img
  - docker push ytodorov93/worker-img
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'fib-app'
  env: 'Fibapp-env'
  bucket_name: 'elasticbeanstalk-us-east-1-365181020201'
  bucket_path: 'fib-app-multi'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY