version: "3"
services:
  client:
    image: "ytodorov93/client-img"
    mem_limit: 128m
    hostname: client
  api:
    image: "ytodorov93/server-img"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "ytodorov93/worker-img"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  nginx:
    image: "ytodorov93/nginx-img"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"